core/src/routing/filter/impls/path.rs
examples/basic_auth.rs
examples/sse_chat.rs
examples/todos.rs

1. Global static variables do not need to be wrapped with Arc again
2. Fix module change cause ci fail
By the way, the project doesn’t seem to be formatted with [rustfmt](https://github.com/rust-lang/rustfmt), I’m not sure if you’re willing to do this, so I didn’t use it rashly either

chore: remove unnecessary arc

---

src/lib.rs

In the current code, if all features are not allowed, a single feature cannot be used

fix: allow single feature on extra

---

core/Cargo.toml
core/src/fs/mod.rs
core/src/fs/named_file.rs
core/src/http/form.rs
extra/src/serve/dir.rs
extra/src/serve/fs.rs

The previous fs used the sync method to operate in an async environment. During concurrent execution, it may be stuck in the executor thread and unable to respond to other requests. Now I rewrite all synchronous methods into asynchronous methods.
Sorry, API break on this PR.
Although tokio's fs relies on the blocking thread pool to perform tasks, this is the best solution at present. Regarding io_ring, firstly, it has too high requirements for the kernel version, and secondly, it is still under development. At present, [tokio-uring](https://github.com/tokio-rs/tokio-uring) is trying out, so we can keep paying attention.
If you need early access, you can take a look at this runtime: [glommio](https://github.com/DataDog/glommio)

refactor: rewrite fs module on async way

---

core/src/depot.rs

use `tracing::instrument` macro need all parameters can be debugged 
```
error[E0277]: `salvo::Depot` doesn't implement `std::fmt::Debug`
--> src/web/visitor.rs:17:1
|
17 | #[tracing::instrument]
| ^^^^^^^^^^^^^^^^^^^^^^ `salvo::Depot` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
|
= help: the trait `std::fmt::Debug` is not implemented for `salvo::Depot`
= note: required because of the requirements on the impl of `std::fmt::Debug` for `&mut salvo::Depot`
= note: 1 redundant requirements hidden
= note: required because of the requirements on the impl of `std::fmt::Debug` for `&&mut salvo::Depot`
= note: required because of the requirements on the impl of `tracing::Value` for `tracing::field::DebugValue<&&mut salvo::Depot>`
= note: required for the cast to …
```

chore: impl debug to depot

---

core/src/http/response.rs
core/src/service.rs

In the previous code logic, the after handler may give up execution because of the response committed. This is unexpected behavior, and the after handler must be executed.

fix: after handler must be executed

---

core/src/depot.rs
core/src/fs/mod.rs
core/src/fs/named_file.rs
extra/Cargo.toml
extra/src/serve/dir.rs

ref: https://github.com/tokio-rs/tokio/issues/3664
`AsyncRead` does not have `read_to_end` semantics, which will result in io operations several times that of blocking read, which will cause chunked operations to become expensive
So, now it is rewritten as a sync operation of spawn_blocking. After testing, the performance is significantly improved 
At the same time, rewrite the std read dir missed in the serve service into an async mode(it is also a product of spawn blocking)

refactor: rewrite chunked file

---

core/src/service.rs

This warning is annoying when status code is error such as 404. And it cannot give correct information at that time.

Avoid warning when errors

---

README.md
core/Cargo.toml
core/src/http/form.rs
core/src/lib.rs

`tempdir` is archived and merged into [tempfile](https://github.com/Stebalien/tempfile)
if rust minimum supported version upgrade to 1.59.0, we can use [available_parallelism](https://doc.rust-lang.org/nightly/std/thread/fn.available_parallelism.html) instead of `num_cpus` crate

chore: repalce tempdir

---

README.md

Since fn_handler is deprecated and the current deprecated function already points to the `handler` macro anyway. I figured it would be best to update the `README.md` to reflect these changes.

Update readme to remove deprecated fn_handler

---

core/src/routing/filter/mod.rs

- Change "allow path method" to "allow patch method" in `filter::patch` documentation

Fix typo in doc

---

crates/core/src/http/request.rs
examples/db-mysql-rbatis/Cargo.toml

Salvo has insecure issue like hyper： https://github.com/hyperium/hyper/issues/3111
When read body to bytes, we should force set max size. If we don't want to always set max size when call functions every time.
We can use default secure max size as default value.

Force set max size when read body to bytes

---

Cargo.toml
crates/core/Cargo.toml
crates/core/src/conn/acme/config.rs
crates/core/src/conn/acme/mod.rs
crates/core/src/conn/acme/resolver.rs
crates/core/src/http/request.rs
crates/core/src/routing/filter/path.rs

`std::sync::RwLock` is more general and in most cases it not slow.
https://users.rust-lang.org/t/which-mutex-to-use-parking-lot-or-std-sync/85060/5

Remove parking_lot, use std::sync

---

crates/oapi-macros/src/endpoint/attr.rs

修复endpoint宏attr拼写错误后，报的提示中tag少加一个s

fix：repair openapi error description of attrs

---

crates/oapi/Cargo.toml
crates/oapi/src/lib.rs
crates/oapi/src/rapidoc/mod.rs
crates/oapi/src/scalar/mod.rs
crates/salvo/src/lib.rs
examples/oapi-todos/src/main.rs

Add support for scalar as alternative for swagger ui

---

crates/oapi/src/scalar/mod.rs

jsdelivr is half the size of unpkg so it loads faster and provides a better user experience with the smaller bundle size. This is our default cdn now.

fix: update scalar import to improved cdn

---

README.md

In the ## Features section, replace period at the end of the final two lines with a semi-colon to match pattern set by earlier lines.

Improve README feature section formatting consistency

---

crates/oapi/src/lib.rs
crates/oapi/src/openapi/tag.rs
crates/oapi/src/openapi/xml.rs

1. Remove duplicated comment.
2. Add test case for `openapi/tag.rs` and `openapi/xml.rs`

tests: add test case for openapi/tag and openapi/xml

---

crates/oapi/src/openapi/example.rs
crates/oapi/src/openapi/request_body.rs
crates/oapi/src/openapi/response.rs

1. `./crates/oapi/src/openapi/example.rs` 100%
2. `./crates/oapi/src/openapi/request_body.rs` 100%
3. `./crates/oapi/src/openapi/response.rs` 95.35%

tests: add testcases for `openapi/response` && `openapi/request_body` && `openapi/example`

---

crates/oapi/src/openapi/content.rs
crates/oapi/src/openapi/encoding.rs
crates/oapi/src/openapi/schema/mod.rs

1. `crates/oapi/src/openapi/content.rs` 94.44%
2. `crates/oapi/src/openapi/encoding.rs` 100.00%

tests: add testcases for `openapi/content` && `openapi/encoding`

---

crates/oapi/src/openapi/external_docs.rs
crates/oapi/src/openapi/header.rs
crates/oapi/src/openapi/info.rs
crates/oapi/src/openapi/mod.rs

1. `openapi/external_docs.rs` 100%.
2. `openapi/header.rs` 100%.
3. `openapi/info.rs` 100%.

tests: add testcases for openapi mods

---

crates/core/src/writing/mod.rs
crates/oapi/src/openapi/path.rs
crates/oapi/src/openapi/server.rs

1. `crates/oapi/src/openapi/path.rs` 100%.
2. Fix typo in `crates/core/src/writing/mod.rs:32`.
3. Fix bug when `Servers` insert an existed `Server`, the json schema does not change as expected.

tests: add testcases for openapi/path

---

crates/core/src/http/request.rs
crates/oapi/src/openapi/mod.rs

1. `crates/oapi/src/openapi/mod.rs` 95.54%.
2. Fix `Request::queries_mut()`returns an unmutable reference.

tests: add testcases for `openapi/mod.rs`

---

.gitignore
crates/oapi/Cargo.toml
crates/oapi/src/extract/parameter/cookie.rs
crates/oapi/src/extract/parameter/header.rs
crates/oapi/src/extract/parameter/path.rs
crates/oapi/src/extract/parameter/query.rs

1. In `salvo_oapi`, we enable `test` feature from `salvo_core`, in order to build `hyper::Request` with `TestClient`.
2. `crates/oapi/src/extract/parameter/cookie.rs` 97.67%.
3. `crates/oapi/src/extract/parameter/header.rs` 97.44%.
4. `crates/oapi/src/extract/parameter/path.rs` 96.30%.
5. `crates/oapi/src/extract/parameter/query.rs` 97.62%.

Add testcases for `crates/oapi/src/extract/parameter/*.rs`

---

crates/core/src/catcher.rs
crates/core/src/conn/proto.rs
crates/core/src/http/response.rs
crates/core/src/service.rs
crates/extra/src/logging.rs
examples/cors/src/main.rs
examples/logging/src/main.rs

Add hoops support to Service

---

crates/rate-limiter/src/fixed_guard.rs
crates/rate-limiter/src/lib.rs
crates/rate-limiter/src/sliding_guard.rs

resolve #626 
- Add `add_headers` field to the `RateLimiter` struct
- Add `add_headers` function to the `RateLimiter` struct
- Add `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers to the response if the `add_headers` is true
- Add `remaining`, `reset` and `limit` functions to the `RateGuard` trait, to get the infos

Support ratelimit headers

---

crates/core/src/service.rs

Response body should be empty for HEAD request , but currently the response body will be set if error happens like 5xx or 4xx.
This PR fixed it.
As the `Method` struct already implemented `PartialEq` and `Eq`, i just used `==` and `!=` for comparing the method values.

Ignore response body for HEAD request even error happened

---

examples/graceful-shutdown/Cargo.toml
examples/graceful-shutdown/src/main.rs

Add：shutdown_graceful_example.
The Salvo server will graceful shutdown when recv Ctrl+C.

add: graceful shutdown example

---

crates/compression/src/lib.rs

The compression crate uses cfg_attr(docsrs) to use nightly docs features but does not actually declare those nightly features, breaking all downstream consumers of salvo.
This fixes that by enabling the appropriate nightly feature.

Add cfg_attr(docsrs) to compression crate

---

crates/core/src/routing/filters/others.rs

Requests that come from http2 use the :authority headers and might not include  the Host header, so they won't work with the host filter.
This PR makes the host filter check for both, first the :authority then the Host header. If the fix-http1-request-uri feature is enabled, then it only checks the authority.

Fix host filter in http2

---

crates/core/src/conn/acme/listener.rs
crates/core/src/conn/native_tls/listener.rs
crates/core/src/conn/openssl/listener.rs
crates/core/src/conn/rustls/listener.rs
crates/core/src/conn/tcp.rs

Close https://github.com/salvo-rs/salvo/pull/702

fix: HTTP/1.1 Always has HTTP Scheme

---

crates/serve-static/src/lib.rs

When using serve-static with static_embed and defaults:
Router::with_path("<**>").get(static_embed::<Assets>().defaults("index.html"));
with a non-root folder with a default file ("index.html"):
├─ index.html
└─ foo/
└─ index.html
trying to GET the "/foo" path results in a redirect loop, with salvo adding an extra "/" after each iteration: "/foo//////////////////".
This is because of the code in embed.rs that tries to redirect from "/foo" to "/foo/":
135 |     if embedded_file.is_some() && !req_path.ends_with('/') && !req_path.is_empty() {
136 |         redirect_to_dir_url(req.uri(), res);
137 |         return;
138 |     }
where req_path was built with:
123 |  let req_path = format_url_path_safely(&req_path);
but `format_url_path_safely()` always strips the final slash(es), which means …

Fixes redirect loop in serve-static.

---

crates/core/src/conn/rustls/config.rs

Hello, 
I rely on Caddy to automatically generate and renew TLS certificates. By default, they use the ED25519 algorithm to generate a private key.
To make use of their certificates, I included the EC private keys in the rustls configuration.
Let me know if I forgot something or if I did something wrong.
Thank you for this amazing project!

Adding EC private keys to rustls config

---

crates/core/src/http/request.rs
crates/core/src/routing/filters/path.rs
crates/core/src/routing/mod.rs
crates/core/src/routing/router.rs
crates/core/src/serde/request.rs
crates/oapi/src/extract/parameter/path.rs
crates/oapi/src/swagger_ui/mod.rs
crates/proxy/src/lib.rs
crates/serve-static/src/dir.rs
crates/serve-static/src/embed.rs
crates/serve-static/src/lib.rs
examples/static-embed-file/src/main.rs

Save and use router param without wildcard

---

crates/oapi-macros/src/parameter/derive.rs
crates/oapi-macros/src/schema/struct_schemas.rs
crates/oapi/src/openapi/schema/all_of.rs
crates/oapi/src/openapi/schema/any_of.rs
crates/oapi/src/openapi/schema/array.rs
crates/oapi/src/openapi/schema/object.rs
crates/oapi/src/openapi/schema/one_of.rs

Merge from utoipa: https://github.com/juhaku/utoipa/pull/990
Prior to this PR the required attribute was not correctly respected in
all cases. This was due to the fact that the required attribute had the
same weight with the default rule that is checked from the option and some
other serde attributes. Even this works in most cases but lacks control
over explicitly defining required to false when type is not
optional.
This PR fixes this by making clear separation between the default rule
and the manual required attribute with preference on the manually
defined required attribute.

Fix respect required attribute

---

crates/oapi-macros/src/schema/enum_variant.rs

fix: Derive ToSchema not work for unit enum variants

---

Cargo.toml
crates/craft-macros/Cargo.toml
crates/craft-macros/README.md
crates/craft-macros/examples/add.rs
crates/craft-macros/src/craft.rs
crates/craft-macros/src/lib.rs
crates/craft-macros/src/utils.rs
crates/craft/Cargo.toml
crates/craft/README.md
crates/craft/examples/add.rs
crates/craft/src/lib.rs
crates/salvo/Cargo.toml
crates/salvo/src/lib.rs

https://github.com/salvo-rs/salvo/issues/919

feat: Add salvo-craft-macros, solve the issue #919

---

crates/core/src/writing/json.rs
crates/core/src/writing/mod.rs
crates/core/src/writing/text.rs

chore(core::writing): Do not forcibly overwrite the content-type and optimize the code.

---

crates/core/src/server.rs

#923 The graceful shutdown function causes the process to hang when exiting.
stop_forcible should be respected and we should not wait for connections.  display the number of connections instead of saying all.  I need to test graceful behavior more but this allows my program to exit when I stop_forible.

display actual number of connections; don't wait if stop_forcible

---

README.md
README.osc.md
README.zh-hans.md
README.zh-hant.md
crates/cache/README.md
crates/compression/README.md
crates/compression/src/lib.rs
crates/core/src/lib.rs
crates/cors/README.md
crates/csrf/README.md
crates/csrf/src/lib.rs
crates/extra/src/lib.rs
crates/flash/README.md
crates/flash/src/lib.rs
crates/jwt-auth/README.md
crates/jwt-auth/src/lib.rs
crates/macros/src/lib.rs
crates/oapi/README.md
crates/otel/README.md
crates/otel/src/lib.rs
crates/proxy/README.md
crates/proxy/src/lib.rs
crates/rate-limiter/README.md
crates/serve-static/README.md
crates/serve-static/src/lib.rs
crates/session/README.md

- Corrected "Savlo" to "Salvo"
- Changed "offical" to "official"
- Updated the URL for Example Projects
- Improved the sentence "This is official crate" to "This is an official crate"

fix: correct typos and update URLs in README.md

---

crates/core/Cargo.toml
crates/cors/Cargo.toml
crates/craft-macros/Cargo.toml
crates/craft/Cargo.toml
crates/csrf/Cargo.toml
crates/extra/Cargo.toml
crates/flash/Cargo.toml
crates/jwt-auth/Cargo.toml
crates/macros/Cargo.toml
crates/oapi-macros/Cargo.toml
crates/oapi/Cargo.toml
crates/otel/Cargo.toml
crates/proxy/Cargo.toml
crates/rate-limiter/Cargo.toml
crates/salvo/Cargo.toml
crates/serde-util/Cargo.toml
crates/serve-static/Cargo.toml
crates/session/Cargo.toml

Add `rust-version = { workspace = true }` to crates `Cargo.toml`

---

crates/oapi-macros/src/schema_type.rs
crates/oapi/src/lib.rs

- I noticed that ToSchema was missing for these types from std::net.
- This was needed for the [Shuttlings Christmas Code Hunt 2024](https://www.shuttle.dev/cch) (challenge 2).
- I'm not sure about the implementation for `IpAddr` enum. Let me know how it can be improved.

feat: impl ToSchema for Ipv4Addr, Ipv6Addr, IpAddr

---

crates/oapi-macros/src/schema/struct_schemas.rs

When `#[serde(deny_unknown_fields)]` was used, the compilation failed with:
```
64 | #[derive(Debug, Serialize, Deserialize, ToSchema)]
|                                         ^^^^^^^^ could not find `schema` in `salvo`
|
= note: this error originates in the derive macro `ToSchema` (in Nightly builds, run with -Z macro-backtrace for more info)
```
Do we need to add a test for this?

fix: conflict with serde deny_unknown_fields attr

---

crates/salvo/Cargo.toml

只有`salvo-core`中有，`salvo`中没有`matched-path`

feat: add matched-path features in Cargo.toml

---

Cargo.toml
crates/oapi-macros/Cargo.toml
crates/oapi-macros/src/schema_type.rs
crates/oapi/Cargo.toml
crates/oapi/src/lib.rs
crates/oapi/src/openapi/schema/mod.rs
examples/oapi-todos/Cargo.toml

This pull request introduces support for the [compact_str](https://docs.rs/compact_str/) crate in the salvo web framework’s OpenAPI integration. The use of compact_str provides an efficient and lightweight alternative to String, particularly beneficial for scenarios involving small strings, reducing memory overhead without sacrificing usability.
- Implemented support for compact_str in relevant OpenAPI structures and code paths.
- Ensured compatibility with existing String behavior, maintaining seamless integration for developers.
The compact_str crate offers significant performance and memory usage advantages for string-heavy applications. This addition makes salvo more flexible and optimized for use cases where efficient memory utilization is critical, aligning with modern Rust best …

feat: support compact_str for oapi

---

crates/core/src/routing/filters/path.rs
crates/core/src/routing/mod.rs
crates/core/src/routing/router.rs

fix matched-path bug

---

crates/proxy/src/lib.rs

I have a Flask service that inserts three `Set-Cookie` headers during the authentication process. But `salvo-proxy` returns only one of these headers for now. So, I think, we need to make this correction.

fix: bug with colliding headers in `salvo-proxy`

---

examples/acme-http01-quinn/src/main.rs
examples/acme-http01/src/main.rs
examples/acme-tls-alpn01/src/main.rs
examples/affix-state/src/main.rs
examples/basic-auth/src/main.rs
examples/body-channel/src/main.rs
examples/graceful-shutdown/src/main.rs
examples/hello-h3/src/main.rs
examples/hello/src/main.rs

docs(examples): Add code comments for a,b,g,h prefixed examples
- Add documentation to ACME certificate management examples
- Comment basic auth and graceful shutdown implementations
- Document HTTP/3 and QUIC related code
- Explain state management and channel usage
- Clarify multi-language endpoint handlers

docs(examples): Annotate a,b,g,h prefixed examples with code comments

---

examples/proxy-simple/src/main.rs

I found an incorrect comment in a file that might mislead developers. I have corrected it to provide the accurate description.
Changes made:
- Fixed the comment in `salvo\examples\proxy-simple\src\main.rs`
This is my first attempt to contribute to an open-source project, so please let me know if there is anything I can improve. Thank you for reviewing!

fix incorrect comment

---

examples/with-listenfd/src/main.rs

required due to latest version of tokio panicking if not set. https://github.com/tokio-rs/tokio/pull/7166

set listener.set_nonblock to true in listenfd sample

---

.github/workflows/format.yml

Potential fix for [https://github.com/salvo-rs/salvo/security/code-scanning/1](https://github.com/salvo-rs/salvo/security/code-scanning/1)
To fix the issue, we will add a `permissions` block at the root of the workflow file. Since this workflow is for formatting code, it only needs read access to the repository contents. We will set `contents: read` as the minimal required permission. This change ensures that the workflow does not inadvertently gain unnecessary write permissions.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 1: Workflow does not contain permissions

---

crates/macros/src/extract.rs

Fix field name mismatch in Extractible when struct contains r#type field.
```rust
static METADATA: ::std::sync::OnceLock<salvo::extract::Metadata> = ::std::sync::OnceLock::new();
METADATA
.get_or_init(|| {
let mut metadata = salvo::extract::Metadata::new("A");
metadata = metadata
.add_default_source(
salvo::extract::metadata::Source::new(
salvo::extract::metadata::SourceFrom::Body,
salvo::extract::metadata::SourceParser::Smart,
),
);
let mut field = salvo::extract::metadata::Field::new("id");
field = field
.add_source(
salvo::extract::metadata::Source::new(
salvo::extract::metadata::SourceFrom::Param,
salvo::extract::metadata::SourceParser::Smart,
),
);
metadata = metadata.add_field(field);
let mut field = salvo::extract::metadata::Field::new("r#type");
metadata = …
```

fix: Extractible derive
