core/src/routing/filter/impls/path.rs, examples/ws_chat.rs, extra/src/proxy/mod.rs, extra/src/serve/dir.rs, extra/src/sse/mod.rs, extra/src/ws/mod.rs
There are some warnings left, I did not make up my mind to modify
=> chore: impl some clippy advice

core/src/fs/mod.rs
1. seek must double-check
2. file read must have a temporary index to track reading, otherwise it will lose data
=> fix: fix file chunk

macros/src/lib.rs
In the previous process macro, it was assumed that the user obeyed the obscure agreement: 
1. The order of the inputs parameters must be Request, Depot, Response
2. When there are only two inputs, it must be Request，Response
3. When there is only one input, it must be Response
But there are problems with the above conditions:
1. It’s too obscure
2. it’s not flexible enough 
This PR will check the order of the parameters, if it is not correct, an error will be reported and the problem will be pointed out. At the same time, it will allow any two-parameter or one-parameter function without assuming what the two or one parameters is. 
It does not help users to reorder to adapt to the generated code, I think this behavior is a bit excessive, so I did not do it  
error：
```
#[fn_handler]
async …
```
=> feat: make macro more flexible

core/src/fs/mod.rs, extra/src/serve/dir.rs
1. `FileChunk<T>` genericization is easy to test, and there is no break change 
2. Allow `StaticDir` to configure chunk size, the default is 1M，the default 65535 of `NamedFile` is too small, which will cause a lot of unnecessary io behaviors. At present, any file may have a size of M
=> feat: allow static dir use with chunk size config

core/src/routing/filter/impls/path.rs
=> fix: fix num with no limit

core/src/http/response.rs, extra/src/compression/mod.rs, extra/src/serve/mod.rs
1. fix the wrong implementation of stream 
2. allow users to set the lower limit of compression
=> fix: Fix body stream impl

extra/src/compression/mod.rs, extra/src/serve/mod.rs
https://github.com/salvo-rs/salvo/issues/29#issuecomment-840434616
=> Fix dir list streaming bug

core/src/http/response.rs, core/src/service.rs, extra/src/serve/dir.rs
1. https://github.com/salvo-rs/salvo/issues/29#issuecomment-840990284
2. commit inner determine whether to repeat the operation
3. listing and dotfiles should not be turned on by default, this will cause security issues
=> fix: fix dir set code

core/src/server.rs
I think this should be print when success.
=> this should be successful info.

core/src/routing/mod.rs
skip reset handlers when code is redirection or not success
=> FlowCtrl: skip reset handlers

core/src/listener/rustls.rs, core/src/routing/mod.rs, examples/basic_auth.rs, extra/src/basic_auth/mod.rs
=> BasicAuthValidator async fn validate

core/src/depot.rs, core/src/service.rs
add depot keys to debug message.
=> Depot debug

core/src/depot.rs, core/src/service.rs, extra/src/jwt_auth/mod.rs
it should be TokenData, not Claims.
=> Jwt auth data

README.md, README_ZH.md, core/src/lib.rs, core/src/server.rs, examples/basic_auth.rs, examples/compression.rs, examples/cors.rs, examples/custom_error_page.rs, examples/custom_filter.rs, examples/file_list.rs, examples/handle_error.rs, examples/hello_world.rs, examples/join_listeners.rs, examples/multi_servers.rs, examples/proxy.rs, examples/remote_addr.rs, examples/routing.rs, examples/size_limiter.rs, examples/sse.rs, examples/sse_chat.rs, examples/tls.rs, examples/tls_reload.rs, examples/todos.rs, examples/upload_file.rs, examples/upload_files.rs, examples/work_with_tower.rs, examples/ws.rs, examples/ws_chat.rs, extra/src/sse/mod.rs
Use 127.0.0.1 in example and add tracing message
=> Use 127.0.0.1 in example

core/src/fs/named_file.rs, core/src/service.rs
I don't want to always handle when NamedFile is not exist or build failed, just want to send it, if it is not exists, just show 404 page.
=> Add send_file to NamedFile

README.md, README.zh-hans.md, README.zh-hant.md
=> Fixed example command

.gitignore, examples/postgres-sqlx/Cargo.toml, examples/postgres-sqlx/src/main.rs
=> Add `sqlx` Example

examples/ws-chat/src/main.rs
There were few JavaScript errors causing example to not work. Mainly variable names. Changed them to make the browser client work.
=> Fixed minor issues in javascript

core/src/http/request.rs, examples/todos/src/main.rs
https://github.com/salvo-rs/salvo/issues/117
=> Rename Request extract_* to parse_*

examples/mongodb/Cargo.toml, examples/mongodb/src/main.rs
Simple example of mongodb.
Create user
Get user by user name
Get all users
=> mongodb sample

crates/core/src/http/request.rs
=> feat: add has_mime in request

examples/graphql/Cargo.toml, examples/graphql/src/main.rs, examples/graphql/src/mutation.rs, examples/graphql/src/query.rs, examples/graphql/src/schema.rs
=> Add simple graphql example

examples/todos-openapi/Cargo.toml, examples/todos-openapi/README.md, examples/todos-openapi/src/main.rs
example todos-openapi using utoipa
=> example todos-openapi

crates/core/src/http/mod.rs
=> Fix unresolved import `crate::http::version_from_alpn`

crates/core/src/catcher.rs, crates/core/src/lib.rs, crates/core/src/routing/mod.rs, crates/core/src/service.rs, crates/core/src/test/request/builder.rs, examples/custom-error-page/src/main.rs
Use Handler to replace Catcher trait.
=> Enhance catch error feature

crates/extra/src/compression.rs
=> Add application/wasm into default content types

.github/workflows/release.yml, CHANGELOG.md, README.md, crates/core/src/catcher.rs, crates/core/src/conn/acme/cache.rs, crates/core/src/conn/acme/config.rs, crates/core/src/conn/acme/issuer.rs, crates/core/src/conn/acme/listener.rs, crates/core/src/conn/acme/mod.rs, crates/core/src/conn/quinn/client.rs, crates/core/src/depot.rs, crates/core/src/http/errors/parse_error.rs, crates/core/src/http/errors/status_error.rs, crates/core/src/routing/filter/mod.rs, crates/core/src/routing/filter/path.rs, crates/core/src/routing/mod.rs, crates/core/src/writer/redirect.rs, examples/graphql/src/mutation.rs, examples/todos-openapi/src/main.rs
hi,
here are some fixes for typos in comments, plus one in the code as well.
=> misc: fix various typos

Cargo.toml, README.md, README.zh-hans.md, README.zh-hant.md, crates/core/src/extract/mod.rs, crates/core/src/serde/request.rs, crates/macros/src/attribute.rs, crates/macros/src/extract.rs, crates/macros/src/lib.rs, crates/oapi-macros/src/attribute.rs, crates/oapi-macros/src/doc_comment.rs, crates/oapi-macros/src/endpoint/mod.rs, crates/oapi-macros/src/lib.rs, crates/oapi-macros/src/parameter/derive.rs, crates/oapi-macros/src/response/derive.rs, crates/oapi-macros/src/response/mod.rs, crates/oapi-macros/src/schema/feature.rs, crates/oapi-macros/src/shared.rs, crates/oapi/docs/derive_to_parameters.md, crates/oapi/docs/derive_to_response.md, crates/oapi/docs/derive_to_responses.md, crates/oapi/docs/derive_to_schema.md, crates/oapi/src/lib.rs, examples/Cargo.toml, examples/extract-data/src/main.rs, examples/extract-nested/src/main.rs, examples/extract-with-lifetimes/src/main.rs, examples/oapi-todos/src/main.rs, examples/todos-utoipa/src/main.rs
Wrap attribute with salvo for avoid conflict with other crates.
=> Wrap attribute with salvo

Cargo.toml, README.md, README.zh-hans.md, README.zh-hant.md, crates/otel/src/metrics.rs, crates/otel/src/tracing.rs
=> deps: Upgrade opentelemetry

crates/proxy/src/lib.rs
=> feat: Allow setting the client on a Proxy #352

crates/extra/src/websocket.rs
To respond to a ping message a pong message should be created.
=> Add pong message creation to websocket message

crates/oapi/src/lib.rs
Implement ToSchema for PhantomData<T>,Avoiding failure to compile under certain circumstances
=> Implement ToSchema for PhantomData<T>

Cargo.toml, crates/compression/src/lib.rs, crates/core/Cargo.toml, crates/core/src/conn/quinn/builder.rs, crates/core/src/fs/named_file.rs, crates/core/src/http/body/channel.rs, crates/core/src/http/body/mod.rs, crates/core/src/http/body/req.rs, crates/core/src/http/body/res.rs, crates/core/src/http/form.rs, crates/core/src/http/response.rs, crates/core/src/test/response.rs, crates/core/src/writing/seek.rs, crates/extra/src/sse.rs, crates/proxy/src/lib.rs, examples/body-channel/Cargo.toml, examples/body-channel/src/main.rs, examples/sse-chat/src/main.rs, examples/sse/src/main.rs
=> Refactor ResBody and add channel support

crates/core/src/extract/metadata.rs, crates/core/src/serde/request.rs
=> Take body only required when extract data

crates/serve-static/src/dir.rs
=> Remove debug println!

crates/core/src/http/request.rs, crates/core/src/serde/request.rs
=> fix: Parse json data failed if it is empty

crates/core/src/http/response.rs
=> request: Update remove cookie doc

crates/core/src/http/request.rs
=> Read all cookie headers to fill `CookieJar`

crates/core/src/http/body/req.rs, crates/core/src/http/body/res.rs
=> Improve debug info for `ReqBody` and `ResBody`

crates/oapi/src/openapi/server.rs
Add testcases for `openapi/server.rs`.
=> tests: add testcases for openapi/server

crates/oapi/src/openapi/security.rs
Add testcases for `openapi/security.rs`.
`#crates/oapi/src/openapi/security.rs +30.67%`
=> tests: add testcases for openapi/security

crates/oapi/src/openapi/operation.rs
1. `crates/oapi/src/openapi/operations.rs`, 100%.
=> tests: add testcases for `openapi/operations`

crates/oapi/src/openapi/parameter.rs
1. `crates/oapi/src/openapi/parameter.rs` 100%.
=> tests: add testcases for `openapi/parameter.rs`

crates/oapi/src/openapi/schema/all_of.rs, crates/oapi/src/openapi/schema/any_of.rs, crates/oapi/src/openapi/schema/array.rs, crates/oapi/src/openapi/schema/mod.rs, crates/oapi/src/openapi/schema/object.rs, crates/oapi/src/openapi/schema/one_of.rs
1. `crates/oapi/src/openapi/schema/*.rs`, 100%.
=> tests: add testcases for `openapi/schema/*.rs`

crates/core/src/extract/mod.rs, crates/oapi-macros/src/parameter/derive.rs, crates/oapi/src/extract/payload/form.rs, crates/oapi/src/extract/payload/json.rs
Add `Debug` trait on `Extractible`.
=> Add `Debug` constraint to `Extractible` trait

crates/oapi/src/extract/payload/form.rs, crates/oapi/src/extract/payload/json.rs
1. `crates/oapi/src/extract/payload/form.rs` 100%.
2. `crates/oapi/src/extract/payload/json.rs` 100%.
=> tests: add testcases for `extract/payload/*.rs`

crates/core/src/test/mod.rs, crates/core/src/test/request/builder.rs, crates/core/src/test/request/mod.rs
resolve https://github.com/salvo-rs/salvo/issues/632
=> Make the `SendTarget` trait a public trait

crates/core/src/service.rs
resolve https://github.com/salvo-rs/salvo/issues/635
=> Pass the request local and remote addr to the `Service::hyper_handler` function

crates/core/src/conn/tcp.rs
=> Add local_addr and ttl functions to `TcpAcceptor`

crates/oapi-macros/src/schema/mod.rs
Fix https://github.com/salvo-rs/salvo/discussions/602#discussioncomment-8061703
=> fix: custom symbol for schema error with generic type

crates/proxy/src/lib.rs
=> proxy: Insert to existing headers and allow to call rest handlers

crates/core/src/http/body/res.rs
=> Improve `ResBody` error debug information

crates/core/src/routing/router.rs, crates/oapi/src/endpoint.rs, crates/oapi/src/lib.rs, crates/oapi/src/openapi/mod.rs, crates/oapi/src/openapi/security.rs, crates/oapi/src/routing.rs, crates/salvo/src/lib.rs
=> Add OpenAPI functions to `Router`.

crates/serve-static/src/dir.rs
add static dir file size view to mb gb
1000 base not 1024   mac unix use 1000 windows use 1024
98595176 -> 98.5 MB
1 KB
999 bytes
1 MB
999.9 KB
1 GB
999.9 MB
1 TB
999.9 GB
1 PB
999.9 TB
=> 🎨  display static file size to mb kb gb tb pb eb

crates/core/src/server.rs
=> fix race on graceful shutdown

crates/oapi/src/extract/payload/file.rs, crates/oapi/src/extract/payload/mod.rs, examples/oapi-upload-file/Cargo.toml, examples/oapi-upload-file/src/main.rs, examples/oapi-upload-files/Cargo.toml, examples/oapi-upload-files/src/main.rs
=> Add `FormFile` and `FormFiles` to OpenAPI

examples/Cargo.toml, examples/otel-jaeger/Cargo.toml, examples/otel-jaeger/README.md, examples/otel-jaeger/src/server1.rs, examples/otel-jaeger/src/server2.rs
=> fix: example otel-jaeger not work

crates/serve-static/src/dir.rs
There is one more }  in the css
=> fix: html css style

crates/core/src/conn/quinn/builder.rs, crates/core/src/conn/rustls/config.rs, crates/core/src/lib.rs, crates/core/src/server.rs, crates/salvo/src/lib.rs
=> fix: HTTP/3 realization doesn't work

crates/core/src/http/body/req.rs
=> fix: Tokio runtime panic when using QuinnListener

crates/compression/src/lib.rs
=> fix: Compression does not set body back if body can not compress

crates/core/src/http/errors/status_error.rs
=> fix: Fix concatenation issue in `StatusError` display

crates/core/src/serde/request.rs, crates/macros/src/extract.rs, crates/oapi-macros/src/endpoint/attr.rs, crates/oapi-macros/src/feature/items.rs, crates/oapi-macros/src/operation/request_body.rs, crates/oapi-macros/src/parameter/mod.rs, crates/oapi-macros/src/parse_utils.rs, crates/oapi-macros/src/response/parse.rs, crates/oapi-macros/src/schema/mod.rs, crates/oapi-macros/src/shared.rs
Allow use ident as extractible source from attribute and allow lit str as  oapi schema name attribute.
Close #832
=> More flexible attribute value for macros

crates/core/src/routing/filters/path.rs
https://gitee.com/salvo-rs/salvo/issues/IAIVST
=> fix: CombWisp match is not correct

crates/csrf/src/lib.rs, crates/extra/src/basic_auth.rs, crates/extra/src/request_id.rs, crates/jwt-auth/src/lib.rs, examples/csrf-cookie-store/src/main.rs, examples/csrf-session-store/src/main.rs
=> fix: Request Id should use header_name as headers key

crates/oapi/src/extract/parameter/cookie.rs, crates/oapi/src/extract/parameter/header.rs, crates/oapi/src/extract/parameter/query.rs
=> oapi: Give extractors `REQUIRED` default value

crates/core/src/server.rs
=> fix: higher-ranked lifetime error regarding config_stream

examples/with-sentry/Cargo.toml, examples/with-sentry/src/main.rs
add with-sentry example for #855
=> doc: add with-sentry example

crates/core/src/service.rs
=> fix: Status Code not set correct when not found

crates/core/src/conn/quinn/builder.rs, crates/core/src/http/request.rs, crates/core/src/service.rs
=> fix: Accepting a Browser Initiated WebTransport Session Always Fails

crates/oapi-macros/src/response/link.rs, crates/oapi-macros/src/schema_type.rs
I cloned the repository, but there will be an error during cargo build.
=> fix: cargo build fail

crates/proxy/src/hyper_client.rs, crates/proxy/src/reqwest_client.rs
=> fix(proxy): Ignore case of WS upgrade type (#974)

crates/oapi/Cargo.toml
=> fix: remove test features to dev

ECOSYSTEM.md
- Added `Community maintained modules` section
- Added `Project showcase` section
- Corrected formatting issues
#965
=> docs: update ECOSYSTEM.md with new sections and format corrections

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Salvo Guru](https://gurubase.io/g/salvo) to Gurubase. Salvo Guru uses the data from this repo and data from the [docs](https://salvo.rs) to answer questions by leveraging the LLM.
In this PR, I showcased the "Salvo Guru", which highlights that Salvo now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to disable Salvo …
=> Introducing Salvo Guru on Gurubase.io

crates/oapi-macros/src/response/mod.rs, examples/__oapi-test/Cargo.toml, examples/__oapi-test/src/main.rs
=> fix(oapi): Inconsistent separator in some oapi macros

ECOSYSTEM.md
Hi, this project is a monitoring web application built with Salvo. I would like to add my project to the markdown document to gain more attention.
Thanks~
=> Adding 'System-Monitor-Server' project case.

examples/todos/src/main.rs
An url is now in the index page in order to go to the todo page.
=> fix(404 error): on the todo example

crates/core/src/service.rs
=> fix spelling mistake

Cargo.toml, crates/core/src/conn/openssl/config.rs, examples/todos/src/main.rs
lock to version `< 0.10.70`, will fix it later
=> fix: openssl lifetime issue when use version 0.10.70

crates/core/src/server.rs
=> fix: spelling mistake

ECOSYSTEM.md
=> add mvt server to ecosystem

crates/extra/src/concurrency_limiter.rs
=> limit MaxConcurrency

crates/extra/src/concurrency_limiter.rs, crates/extra/src/request_id.rs
=> 日志和respons 中追加requestid

crates/extra/Cargo.toml, crates/extra/src/basic_auth.rs
=> Allow set basicauth realm value

crates/core/src/routing/mod.rs, crates/extra/src/logging.rs, crates/oapi/docs/derive_to_parameters.md, crates/oapi/docs/derive_to_schema.md, crates/oapi/docs/endpoint.md, crates/oapi/src/openapi/schema/object.rs, crates/proxy/src/lib.rs, examples/logging/src/main.rs
=> Logging `StatusError` if it exists in Response body
